apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<github-username>/argocd-lab-template' # Update to match your fork.
    path: portal
    targetRevision: HEAD
  destination:
    namespace: portal
    name: in-cluster # Update this value.
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
